name: Helm Release
on:
  push:
    branches:
      - gh-actions
    paths:
      - "helm/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "travisgroth"
          git config user.email "travisgroth@users.noreply.github.com"
      - name: Run chart-releaser
        uses: desimone/chart-releaser-action@master
        env:
          CR_TOKEN: "${{ secrets.CI_TOKEN }}"
        with:
          charts_dir: helm
          charts_repo_url: https://travisgroth.github.io/reddit-exporter/
